"""Archived narrative batch for Thalantira; no runtime or numerical balance edits."""
import hashlib
import json
from pathlib import Path
from urllib.parse import quote

ROOT = Path(__file__).resolve().parents[1]
BEST = ROOT / '07_Bestiary'
FOLDER = BEST / '03_Thalantira'
REPORT = BEST / '_audit'
GAME = ROOT / '10_Game Project/Tales of The Dark Time'
REG = '03_Region/11_Thalantira/Threat.md'
WORLD = '03_Region/11_Thalantira/Thalantira.md'
MOUNTAIN = '03_Region/11_Thalantira/Cities & Town/Kuil Udara Gunung Ungu.md'
URU = '05_Karakter & Tokoh Penting/11_Entitas_Purba/Uru.md'
P6 = '08_Story/02_Prologue/06_Kutukan_dan_Pengorbanan.md'
P7 = '08_Story/02_Prologue/07_Tiga_Kuil_Penjaga.md'
P8 = '08_Story/02_Prologue/08_Ujian_Para_Pelindung.md'
P9 = '08_Story/02_Prologue/09_Pesan_dari_Ketiadaan.md'
UNTOLD = '08_Story/03_The_Untold_Story/03_Penjaga_Kuil_Api_Neraka.md'

# Description, form, behavior, habitat, tale title, tale, sources, unresolved.
ENTRIES = {
'Abyssal_Piranha': (
 'Ikan pemangsa Thalantira yang rahangnya mampu merobek zirah adamantite. Tubuh yang jauh lebih kecil daripada para raksasa laut pulau ini membuatnya mudah terabaikan. Kilatan singkat di antara karang dapat menjadi satu-satunya tanda sebelum air yang semula kosong dipenuhi gerakan menggigit.',
 'Tubuhnya pipih dari samping dan padat di belakang kepala, dengan pangkal ekor kuat untuk menyentak melawan arus. Sisik kelabu kebiruan memantulkan cahaya ungu dari pulau sebagai kilatan patah. Rahang bawah sedikit menonjol; gigi segitiga tersusun rapat sehingga mulut yang tertutup tetap tampak bergerigi. Sirip pendek menjaga tubuhnya tidak mudah tersangkut di lorong karang. Saat berbalik serentak, kawanan terlihat seperti serpihan logam yang dituang ke dalam air.',
 'Buas dan cepat bereaksi terhadap mangsa yang terdesak. Kawanan menyebar mengikuti celah, lalu berkumpul ketika salah satu menemukan kesempatan menggigit. Gangguan besar membuatnya berpencar sementara sebelum mendekat dari sisi lain. Pertahanan tubuh mangsa tidak selalu menghalanginya, tetapi sifat perobek zirah tidak berarti ia memakan logam sebagai makanan utama. Dalam pengungkapan Prologue, piranha termasuk makhluk air yang muncul ketika kedamaian pulau runtuh.',
 'Perairan Thalantira merupakan habitat asal. Celah pada cincin karang, saluran sempit dengan arus deras, dan kantong air terlindung di balik batu cocok sebagai wilayah jelajah tambahan. Tempat itu menyediakan ruang bagi ikan kecil untuk berlindung dari raksasa laut. Kemunculan kawanan dalam kekacauan di daratan Prologue tidak menetapkan bahwa spesies ini lazim hidup tanpa air.',
 'Kilatan di Celah Karang',
 'Seekor ikan besar berlindung dari pusaran di antara dua dinding karang. Ruang itu tampak kosong sampai kilatan kecil bergerak di dekat ekornya. Ia mengibas kuat, mengusir satu bayangan, tetapi gerakan itu membawanya semakin dalam ke lorong sempit.\n\nDari bawah batu, kilatan lain datang. Air bergolak sesaat, lalu arus kembali berjalan seperti sebelumnya. Kawanan piranha menyebar ke celah masing-masing. Di atasnya, gelombang terus memukul benteng karang; tak ada perubahan pada permukaan yang menunjukkan apa yang baru saja terjadi.',
 [REG, P9], ['Habitat mikro, rupa, dan kisah ekologis adalah usulan; kemunculan Prologue tidak membuktikan adaptasi darat.']),
'Abyssal_Treant': (
 'Pohon berjalan yang membawa aura korupsi di hutan Thalantira. Diamnya menyerupai ketenangan batang tua, tetapi akar dapat terangkat dan bergerak mengejar. Pertemuannya dengan Rama memperlihatkan bahaya yang lebih ganjil daripada pemangsaan: ia menyerang orang yang hendak menyelamatkan Shinta sambil membiarkan perempuan itu tetap berada dalam kedamaian palsu pulau.',
 'Batangnya besar dan berpilin, dengan pangkal akar yang membuka seperti jemari mencengkeram tanah. Kulit kayu gelap terbelah oleh rongga panjang; di antaranya tampak lembap seolah bagian dalam pohon tak pernah mengering. Cabang rendah menjulur sebagai sulur penahan, sedangkan tajuk berat menyamarkan gerakan tubuh di antara pepohonan. Rancangan ini mempertahankan rupa pohon, tanpa memerlukan wajah manusia yang dipahat pada batangnya. Ketika berjalan, tanah terangkat bersama akar sebelum jatuh kembali dalam gumpalan.',
 'Berbahaya, tetapi tidak selalu menyerang semua orang dengan cara sama. Treant yang dihadapi Rama menghalanginya mendekati Shinta dan menghantamnya hingga terlempar ke perahu. Sikap melindungi Shinta tidak membuatnya penjaga yang baik hati: tindakan itu mempertahankan pemisahan pasangan tersebut. Saat ilusi pulau tersingkap dalam Prologue, Treant juga hadir di antara monster darat. Pola serangan selektif pada Shinta merupakan kejadian tertentu, bukan jaminan bahwa orang yang bersikap tenang akan diabaikan.',
 'Hutan pedalaman Thalantira, terutama jalur rapat di antara pantai dan pusat pulau. Akar besar dan cahaya yang terhalang tajuk cocok untuk menyembunyikan tubuhnya. Hutan yang tampak tenteram saat kedatangan Hector dan Cassian harus dibaca bersama pengungkapan ilusi; keindahan tersebut tidak cukup untuk memastikan suatu jalur bebas Treant.',
 'Akar di Antara Dua Tangan',
 'Rama telah menemukan Shinta, tetapi belum berhasil membawanya pulang. Istrinya masih menari di dalam ketenteraman yang tidak dapat ia bagikan. Ketika Rama mencoba menariknya pergi, sulur kayu bergerak di antara mereka.\n\nTreant tidak menerkam Shinta. Ia justru menghadapkan tubuhnya kepada Rama, seolah tangan sang suami merupakan gangguan yang harus disingkirkan. Rama melawan sampai akar besar menghantam dan melemparkannya ke perahu yang rusak. Hutan kembali menutup jarak di antara mereka; istrinya masih berada di pulau ketika ia kehilangan kesempatan mendekat.',
 [REG, P6, P7, P9], ['Kisah merangkum P6; rupa tambahan usulan. Penampakan Shinta pada akhir P9 tidak dijadikan aturan kebangkitan Treant.']),
'Behemoth_Cangkang_Hitam': (
 'Pelindung Kuil Tanah di barat Thalantira yang tubuhnya menyerupai benteng hidup. Serangan Hector dan Cassian pernah terpental tanpa melukainya. Di balik sosok mengerikan itu terdapat penjaga yang mampu berbicara, bercanda, serta menolong; wataknya tidak dapat dijelaskan hanya dengan sebutan binatang buas.',
 'Wujud aslinya memadukan postur banteng dengan reptil purba: otot masif, kulit keras seperti cangkang baja berwarna cokelat gelap, dan sepasang tanduk ungu yang melengkung di atas kepala. Cakar emas menyangga tubuh beratnya, sementara ekor berduri memanjang seperti cambuk. Taring memenuhi mulut yang mengembuskan uap panas. Gambaran menyerupai gajah pada peta adalah tafsiran keliru Cassian. Dalam wujud manusia, Behemoth tampil sebagai pria berperut buncit dengan pembawaan seorang paman jenaka.',
 'Ganas terhadap penyusup yang dianggap ancaman, tetapi mampu menghentikan serangan setelah mengenali esensi Hydra pada pengunjung. Ia kemudian menyerahkan Emblem Tanah dan membantu menghadapi kakaknya, Void Wyrm. Perilaku ramah ini mendahului pengungkapan Uru, ketika tubuh para penjaga dipaksa bermutasi dan mereka berbalik menyerang. Sesudah pengejaran berakhir, para penjaga kembali terlihat dalam wujud manusia yang sadar dan tunduk kepada Uru. Keganasan pada fase tersebut tidak menghapus seluruh riwayat kehendak serta percakapannya.',
 'Kuil Tanah berada dalam gunung batu berongga di padang tandus sebelah barat, dicapai melalui lorong bercabang. Bentang gersang ini berbeda dari hutan timur yang menuju kuil Hydra. Ruang penjaga dan altar emblem merupakan lokasi yang dicatat Prologue; tidak diperlukan kota atau perkampungan baru untuk menjelaskan keberadaannya.',
 'Cakar yang Berhenti',
 'Pedang Hector memantul dari tubuh Behemoth. Cahaya Cassian juga gagal meninggalkan luka. Ketika cakar emas terangkat, keduanya hampir tidak mempunyai kesempatan menghadapi hantaman berikutnya.\n\nLalu Behemoth melihat sisa esensi air pada pakaian mereka. Gerakannya berhenti. Sosok yang baru saja memenuhi ruangan dengan ancaman berubah menjadi pria yang menanyakan kabar Hydra. Setelah mendengar penjelasan mereka, ia menyerahkan emblem sambil tertawa. Hector menerima benda itu dengan kikuk: ujian yang dikiranya harus dimenangkan dengan kekuatan berakhir karena sang penjaga mengenali jejak adiknya.',
 [P7, P8, P9, URU], ['Anatomi mengikuti koreksi eksplisit P8, bukan tafsiran peta P7. Ketahanan naratif tidak menetapkan immunity gameplay. Sebutan saudara/Ayah tidak membuktikan silsilah biologis.']),
'Crystal_Basilisk': (
 'Kadal raksasa dengan tatapan yang dikenal membekukan korbannya. Di bawah cahaya ungu Thalantira, tubuhnya dapat disangka gugusan kristal sebelum kepala bergerak mengikuti sesuatu yang lewat. Bahayanya tidak hanya datang dari rahang: menatap balik untuk memastikan bentuknya dapat menjadi bagian paling buruk dari sebuah perjumpaan.',
 'Tubuhnya rendah dan panjang, ditopang kaki tebal dengan jemari bercakar yang menyebar pada batu. Sisik besar di punggung membentuk bidang bening keruh, sedangkan bagian perut tampak lebih rapat dan kusam. Tonjolan kristal tumbuh mengikuti tengkuk hingga pangkal ekor, menyerupai pecahan mineral yang tertanam pada kulit. Kelopak keras membingkai mata terang. Ketika kepala terangkat, pantulan pada sisik bergerak lebih dahulu daripada tubuhnya, membuat posisi mata sulit dibedakan dari kilau batu.',
 'Teritorial dan berbahaya bila didekati. Ia menahan tubuh di tempat, mengangkat kepala, lalu mengikuti gangguan dengan pandangan sebelum bergerak. Ancaman yang terus mendekat dapat memancing serangan terbuka. Keheningan tidak menunjukkan sifat jinak; Basilisk dapat menunggu dari posisi yang hampir tidak berubah. Catatan lama menyebut pembekuannya permanen, tetapi kisah belum menjelaskan batas maupun pemulihannya. Dalam Prologue ia termasuk monster darat yang terlihat setelah selubung damai pulau tersingkap.',
 'Darat Thalantira adalah habitat sumber. Teras batu teduh di peralihan hutan dan lereng Gunung Ungu diusulkan sebagai tempat berdiam, dengan celah untuk menyembunyikan tubuh panjangnya. Penempatan ini tidak berarti Basilisk hidup di dalam lahar atau menghuni ruang inti kristal gunung. Permukaan dingin yang terlindung dan jalur mangsa lebih sesuai dengan rancangan perilakunya.',
 'Kristal yang Menoleh',
 'Seekor pemangsa kecil menyusuri tepian batu, mengikuti gerakan di balik semak. Di depannya, deretan kristal memantulkan langit. Ia berhenti ketika salah satu pantulan bergerak melawan arah cahaya.\n\nKepala Basilisk terangkat perlahan. Pemangsa itu mundur ke balik akar, memutus pandangan sebelum seluruh tubuh panjang muncul dari ceruk. Basilisk tidak mengejar ke hutan rapat. Ia kembali merendahkan kepala, dan lereng kembali tampak seperti batu yang tidak dihuni apa pun.',
 [REG, MOUNTAIN, P9], ['Mikrohabitat dan rincian kristal usulan. Durasi/counter pembekuan belum ditentukan; tidak menambah state atau angka.']),
'Deepwater_Siren': (
 'Penyanyi ilusi dari perairan Thalantira yang dapat menarik pelaut menuju kematian. Suaranya memberi kesan bahwa sesuatu yang dicari berada sedikit lebih dekat daripada kenyataan. Di laut dengan karang tajam dan arus mustahil, kesalahan kecil dalam menilai arah sudah cukup untuk membawa pendengar keluar dari jalur selamat.',
 'Rancangan tubuhnya menampilkan sosok menyerupai manusia pada bagian kepala dan dada, lalu memanjang menjadi ekor bersirip yang menyatu dengan gelap air. Rambut halus terurai mengikuti arus, sementara selaput tipis pada lengan bergetar ketika tubuh berbelok. Wajahnya sukar dipastikan karena riak dan pembiasan terus mengubah garis mata serta mulut. Sisik kebiruan tampak paling terang di tenggorokan. Rupa yang terlihat melalui ilusinya tidak selalu mencerminkan tubuh yang sedang bergerak di bawah permukaan.',
 'Memikat dan berbahaya, dengan kecenderungan mengarahkan mangsa sebelum mendekat. Siren mempertahankan jarak di balik riak, memindahkan sumber nyanyian, lalu menunggu korban kehilangan arah. Ketika terancam, ia dapat menyelam dan memanfaatkan lorong karang untuk memutus pengejaran. Nyanyian lembut bukan tanda keramahan. Kehadirannya tercatat bersama makhluk air pada pengungkapan Prologue, tetapi kemampuan ilusi pribadinya tidak membuktikan bahwa dialah pencipta selubung ilusi seluruh pulau.',
 'Perairan sekitar Thalantira, dengan cekungan dalam di belakang benteng karang sebagai usulan tempat bersembunyi. Gaung pada dinding batu dan gerak air mendukung kesulitan menemukan sumber suaranya. Habitat ini tidak membutuhkan permukiman pelaut di pulau; ancamannya berlaku bagi siapa pun yang mencoba menembus perairan terlarang tersebut.',
 'Nyanyian Tanpa Pantai',
 'Badai membuka sebuah lorong tenang di antara karang. Dari ujungnya terdengar nyanyian, lembut seperti datang dari pantai yang terlindung. Sosok pucat mengambang sebentar di permukaan sebelum lenyap di balik busa.\n\nSiren berenang mengikuti lorong itu sampai dasar laut jatuh menjadi jurang. Nyanyiannya masih terdengar seolah berasal dari daratan. Ketika gelombang menutup jalan masuk, ia berhenti dan mendengarkan air. Pantai yang dijanjikan suaranya tidak pernah ada; hanya karang, kedalaman, dan tubuhnya yang menunggu.',
 [REG, P9], ['Anatomi ekor dan mikrohabitat usulan; bukan identifikasi ras air tertentu atau pencipta ilusi Uru.']),
'Eclipse_Falcon': (
 'Elang Thalantira yang menyelubungi jalur buruannya dengan kegelapan sebelum menukik. Bayangannya dapat terasa seperti awan yang mendadak menutup matahari, padahal langit di sekeliling masih terbuka. Kecepatan serangannya membuat selang antara hilangnya cahaya dan datangnya cakar terasa sangat singkat.',
 'Tubuhnya ramping dengan dada berotot, sayap meruncing, dan ekor yang dapat membuka sebagai kemudi. Bulu hitam berkilau ungu pada tepian, sedangkan kepala kecil serta paruh melengkung memberi siluet tajam. Cakar panjang terlipat rapat saat meluncur. Ketika sayap dibentangkan, batas bulunya larut dalam selubung gelap sehingga ukuran tubuh sulit dinilai dari bawah. Di dekat tebing, hanya kilat mata dan garis paruh yang sesekali memisahkannya dari bayangan batu.',
 'Pemangsa buas yang mengandalkan ketinggian dan kejutan. Ia berputar jauh dari sasaran, memadamkan pandangan di jalur turun, lalu menyerang ketika mangsa berhenti atau berbalik mencari arah. Gangguan dekat tempat bertengger memancing sapuan rendah sebagai peringatan sebelum terjangan berikutnya. Setelah selubung damai Thalantira runtuh, Eclipse Falcon termasuk makhluk yang memenuhi langit Prologue. Kegelapan yang dibawanya tidak dengan sendirinya menyatakan kesetiaan kepada Sangrahal.',
 'Langit Thalantira merupakan wilayah jelajah. Tebing terjal di jalur utara menuju gunung api cocok sebagai tempat bertengger yang diusulkan, dengan angin naik untuk membantu memperoleh ketinggian. Ia juga dapat melintasi batas hutan, tetapi tidak harus bersarang di Kuil Udara atau menjadi peliharaan Void Wyrm agar berbagi ruang langit tersebut.',
 'Awan yang Mendahului Cakar',
 'Seekor burung kecil meninggalkan celah tebing ketika cahaya kembali menyentuh batu. Ia terbang menuju pepohonan, mengikuti jalur yang biasanya terlindung dari angin. Di tengah lintasan, cahaya hilang lagi.\n\nBurung itu membelok sebelum bayangan pertama menyentuhnya. Cakar Falcon menyambar udara kosong dan menyapu daun di tepi hutan. Sang pemburu naik kembali tanpa bersuara. Di celah tempat burung kecil bersembunyi, terang pulih perlahan, tetapi langit yang terbuka tidak lagi terlihat seperti jalan bebas.',
 [REG, P8, P9], ['Perilaku berburu dan tempat bertengger usulan; tidak menetapkan faksi Sangrahal atau hubungan peliharaan.']),
'Hydra_Jurang': (
 'Penjaga Emblem Air di timur Thalantira, berwujud naga ular kolosal yang dikenal sebagai penelan samudra. Besarnya tubuh tidak mencerminkan cara ia selalu menyambut tamu. Hydra pernah memberikan jalan dan pertolongan kepada Hector serta Cassian, sebelum kuasa Uru mengubah pertemuan ramah itu menjadi bagian dari kengerian pulau.',
 'Kepala dan sebagian tubuhnya saja memenuhi ruang kuil bawah air. Sisik memancarkan kesan kedalaman samudra, taring menjulang seperti pilar, dan matanya menunjukkan kecerdasan yang sadar akan pengunjungnya. Sumber cerita menggambarkannya sebagai naga ular, tanpa menetapkan banyak kepala. Ia juga mengambil wujud perempuan berambut mengalir seperti air terjun malam, mengenakan gaun dari air yang terus bergerak. Setelah mutasi paksa, keindahan air serta sisik itu berubah menjadi rupa rusak yang diterangi ungu.',
 'Mampu berunding, menyambut dengan hangat, dan menyatakan kebencian terhadap pertumpahan darah. Ia membuat pijakan es alih-alih langsung menyerang, memberikan emblem, serta membantu melindungi tamunya dari Void Wyrm. Keramahan tersebut tidak menjadi jaminan keselamatan setelah perintah Uru turun: Hydra ikut dalam serangan yang menewaskan Rama. Kemunculan berikutnya dalam wujud manusia yang berlutut menunjukkan bahwa fase kegilaan itu tidak boleh dianggap sebagai hilangnya kesadaran untuk selamanya.',
 'Kuil Air di sebelah timur, dicapai melalui kawasan berhutan menuju waduk dan ruang luas di bawah permukaan. Tempat itu menjadi pusat tugas penjagaannya. Laut sekitar pulau sesuai dengan identitas kekuatan samudranya, tetapi jalur perpindahan antara kuil dan laut belum dipetakan. Sebutan penjaga air tidak berarti semua makhluk laut merupakan keturunannya.',
 'Pijakan di Atas Air Bah',
 'Air memenuhi ruang kuil ketika kepala Hydra muncul. Hector mengangkat pedang, dan Cassian menyiapkan cahaya untuk menghadapi serangan. Namun napas dingin sang naga justru membentuk pijakan es bagi mereka.\n\nTubuh raksasa itu menyusut menjadi perempuan yang menyapa dengan ramah. Ketika mereka menjelaskan kebutuhan akan emblem, ia mengambilnya dari altar dan menyerahkannya tanpa pertarungan. Mereka pergi membawa kunci sekaligus kebingungan. Kebaikan yang dialami malam itu nyata sebagai tindakan, tetapi belum menjawab pertanyaan Cassian tentang pulau yang terus dihindari sang penjaga.',
 [P7, P8, P9, URU], ['Jumlah kepala tidak ditambahkan. Sebutan Ayah/saudara tidak membuktikan reproduksi biologis. Perilaku dibedakan menurut fase Prologue.']),
'Kraken_Tentacle': (
 'Bagian tentakel raksasa yang menyerang kapal di perairan Thalantira. Apa yang terlihat di permukaan hanyalah anggota tubuh, bukan ukuran utuh pemiliknya. Satu lengkungan yang disangka gelombang dapat berubah menjadi belitan yang menahan lambung, sementara bagian lain tetap bergerak jauh di bawah air.',
 'Tentakelnya tebal, lentur, dan berangsur menyempit menuju ujung. Permukaan luar gelap seperti batu basah, dengan lipatan melingkar yang mengencang ketika mencengkeram. Pada sisi dalam, deretan pengisap besar membantu menempel pada permukaan licin. Bekas air mengalir di antara tonjolan kulit ketika anggota tubuh itu terangkat. Ujungnya dapat menyusup lebih dahulu ke celah karang sebelum bagian yang jauh lebih berat mengikuti. Wujud lengkap makhluk di kedalaman tidak diperlihatkan oleh nama entri ini.',
 'Agresif terhadap sesuatu yang melintasi ruang jangkaunya. Tentakel meraba, menahan, lalu menarik; gerakan yang tampak lambat dapat berubah menjadi hentakan ketika pegangan sudah kuat. Gangguan pada satu bagian membuat belitan menegang atau bergeser ke sisi lain. Melepas satu cengkeraman belum memastikan seluruh ancaman menjauh. Tentakel termasuk manifestasi makhluk air dalam pengungkapan Prologue, tetapi pengamatan itu tidak memastikan berapa banyak individu yang berada di bawah permukaan.',
 'Perairan dalam sekitar Thalantira, terutama jurang di dekat cincin karang sebagai usulan tempat tubuh utamanya tersembunyi. Anggota tubuh dapat menjangkau bagian yang lebih dangkal tanpa membuat keseluruhan makhluk menetap di pantai. Namanya tidak cukup untuk menyamakan pemilik tentakel ini dengan setiap makhluk bernama Kraken di wilayah Nusvanir lain.',
 'Batu yang Ditarik Laut',
 'Sebuah bongkah karang retak oleh gelombang dan jatuh ke saluran sempit. Arus menekannya di antara dinding batu, tempat pusaran biasa menyeret benda-benda dari permukaan. Sesuatu yang gelap melingkari bongkah itu dari bawah.\n\nBelitan mengencang, lalu melepaskan dan mencoba dari sisi lain. Batu akhirnya terguling ke kedalaman. Tentakel mengikuti tanpa memecah permukaan lagi. Saluran kembali terbuka, seolah laut sendiri baru saja memindahkan penghalang yang mengganggu jalannya.',
 [REG, P9], ['Entri tetap bagian tubuh, bukan spesies terpisah. Anatomi utuh, jumlah individu, dan hubungan dengan Kraken wilayah lain belum pasti.']),
'Manta_Ray_Void': (
 'Pari dari kedalaman Thalantira yang meluncur dengan tenang sebelum melepaskan energi mematikan. Tubuhnya menyerupai bayangan lebar yang terlepas dari dasar laut. Pada air gelap, cahaya yang berkumpul di depannya lebih mudah terlihat daripada gerakan sirip yang membawanya mendekat.',
 'Cakram tubuhnya melebar ke samping sebagai sepasang sirip lentur, dengan tepian melengkung yang naik turun mengikuti arus. Punggung gelap memuat bintik pucat menyerupai serpih cahaya, sedangkan bagian bawah kelabu berbaur dengan air keruh. Dua lipatan di dekat mulut membentuk corong pendek saat energi berkumpul. Ekor ramping tertinggal di belakang seperti garis yang sulit diikuti. Kesan kosmis pada rupanya memperkuat nama Void tanpa menjelaskan asalnya sebagai penghuni langit atau ruang antarbintang.',
 'Menghindari benturan langsung, tetapi berbahaya ketika wilayah lintasannya terganggu. Ia membelok lebar untuk menghadap ancaman dan menahan posisi sebelum melepaskan energi. Jika ruang menyempit, pari mundur ke kedalaman alih-alih memaksa cakram tubuh melewati celah kecil. Ketenangan berenangnya tidak membuktikan bahwa ia jinak. Rancangan tingkah laku ini mengembangkan catatan serangan energi; belum ada perjumpaan bernama yang memastikan niat atau kecerdasannya.',
 'Laut dalam Thalantira adalah habitat sumber. Lereng bawah laut di luar karang raksasa diusulkan sebagai jalur meluncur, menyediakan ruang lebar bagi siripnya. Ia tidak ditempatkan di kubah udara atau kawah hanya karena namanya bernuansa kosmis. Daftar makhluk yang tampak dalam pengungkapan Prologue tidak menyebut Manta Ray Void secara khusus.',
 'Cahaya di Bawah Pusaran',
 'Di bawah arus yang mengamuk, seekor pari melewati lereng batu dengan gerakan hampir tanpa suara. Pemangsa lain muncul dari celah dan mengikutinya. Pari itu membelok, memperlihatkan sisi bawah yang semula tersembunyi.\n\nCahaya berkumpul di depan mulutnya. Pemangsa berhenti, tetapi semburan telah membelah air di antara mereka. Endapan naik menutupi lereng. Ketika butir pasir kembali turun, pari sudah meluncur lebih dalam, meninggalkan lorong gelap yang sesaat tadi tampak menyala seperti langit.',
 [REG, WORLD], ['Tidak disebut khusus dalam P9; kisah ekologis dan rupa usulan. Void bukan penetapan elemen runtime atau asal antarbintang.']),
'Megalodon_Phantom': (
 'Hiu hantu Thalantira yang dapat menembus karang ketika memburu. Tempat berlindung yang menghentikan pemangsa lain tidak selalu memutus jalurnya. Siluetnya kadang hilang di balik batu sebelum muncul kembali dari sisi yang tidak memiliki celah cukup lebar untuk tubuh sebesar itu.',
 'Tubuhnya berbentuk torpedo dengan kepala berat, sirip punggung tinggi, dan ekor yang mendorong melalui kibasan lebar. Tepian tubuh tampak kabur seperti dilihat melalui air dengan kedalaman berbeda. Barisan gigi terlihat lebih jelas daripada kulit, membuat rahangnya seolah mendahului bagian lain saat muncul dari kegelapan. Ketika melewati karang, garis sirip dan punggung saling bertumpuk dengan batu tanpa memecahnya. Rupa menyerupai bayangan itu tidak dengan sendirinya menjelaskan apakah ia pernah hidup dalam bentuk lain.',
 'Pemangsa buas yang terus mengikuti jalur mangsa melewati penghalang. Ia mengitari ruang sempit sebelum menerobos karang dari arah yang sulit diantisipasi. Ancaman yang mampu menghadapinya membuat hiu memperlebar putaran untuk mencari sisi terbuka. Gerak menghilang bukan selalu tanda mundur. Megalodon Phantom tercatat di antara makhluk air ketika keadaan asli Thalantira tersingkap; sebutan hantu tidak cukup untuk memasukkannya ke golongan Dhemit atau menyatakan asal arwahnya.',
 'Perairan Thalantira, dengan labirin karang dan tepian jurang laut sebagai habitat tambahan yang sesuai. Di tempat tersebut, kemampuan menembus batu memberi jalur pendek di antara lorong berkelok. Ia tetap digambarkan sebagai penghuni air; kemunculan makhluk laut dalam kekacauan Prologue tidak mengubah seluruh kebiasaan hidupnya menjadi pemangsa daratan.',
 'Jalan yang Tidak Terbuka',
 'Seekor ikan besar menyelinap ke rongga karang setelah melihat sirip di belakangnya. Jalan masuk terlalu kecil bagi hiu. Ia berhenti di ruang gelap, sementara bayangan pemangsa lewat di luar lubang.\n\nLalu gigi muncul dari dinding. Batu tidak retak, dan tak ada pasir yang jatuh. Ikan itu melesat keluar melalui bukaan lain, kembali ke laut yang tadi ingin dihindarinya. Di belakangnya, hiu meluncur melewati karang seolah rongga tersebut tidak pernah memiliki dinding.',
 [REG, P9], ['Sifat phantom tidak membuktikan undead/Dhemit. Rupa dan mikrohabitat usulan; tidak menambah aturan collision atau immunity game.']),
'Nebula_Eye': (
 'Mata kosmis melayang yang melepaskan sinar mematikan ke arah pandangannya. Kehadirannya membuat ruang terbuka di Thalantira terasa seperti tempat yang terus diawasi. Ia tidak perlu mengepakkan sayap untuk mengubah ketinggian, dan diamnya di udara dapat disangka cahaya ganjil sampai pupil berputar mengikuti gerakan di bawah.',
 'Sebuah bola besar menjadi pusat tubuh, dibingkai lapisan berkabut yang berputar perlahan. Irisnya memuat lingkaran warna ungu dan biru kusam, dengan pupil gelap yang tampak semakin dalam ketika cahaya berkumpul. Serabut halus menjuntai dari bagian belakang seperti asap yang menolak terurai. Tidak ada wajah, paruh, atau anggota gerak untuk membantu membaca arah niatnya. Perubahan arah tampak dari pergeseran pupil lebih dahulu, lalu seluruh bola mengikuti dengan putaran lambat.',
 'Mengancam melalui pengamatan dan tembakan dari jarak terbuka. Dalam rancangan perilaku ini, ia berhenti di atas jalur yang menarik perhatiannya, mengikuti satu gerakan, lalu memusatkan cahaya sebelum menyerang. Gangguan dari arah lain dapat membuatnya berputar tanpa berpindah tempat. Menunduk di balik batu tidak menjamin ia telah kehilangan sasaran. Nebula Eye muncul di langit pada pengungkapan Prologue, tetapi nama dan bentuknya tidak membuktikan bahwa ia merupakan mata milik Uru.',
 'Udara di atas Thalantira, terutama celah langit antara tajuk hutan dan tebing pedalaman sebagai usulan wilayah melayang. Ruang terbuka memberi garis pandang panjang, sementara kabut gunung menyamarkan batas tubuhnya. Tidak ada sarang berbentuk bangunan atau tempat pemujaan baru yang diperlukan untuk menjelaskan keberadaannya.',
 'Tatapan di Antara Tajuk',
 'Angin membuka celah pada tajuk, memperlihatkan mata besar yang menggantung di atas hutan. Di bawahnya, seekor makhluk darat berhenti bergerak. Pupil itu terus menghadap ke tempat persembunyiannya meskipun daun kembali menutup pandangan.\n\nCahaya mengumpul, lalu sebuah sinar memotong sela cabang. Batang yang terkena berasap. Makhluk di bawah sudah menyelinap ke lekukan akar, tetapi mata itu belum pergi. Ia berputar sedikit demi sedikit, menunggu gerakan berikutnya di hutan yang mendadak sunyi.',
 [REG, P9, URU], ['Tidak ditetapkan sebagai organ/avatar Uru. Anatomi, garis pandang, dan kisah ekologis adalah usulan naratif, bukan AI gameplay.']),
'Obsidian_Crawler': (
 'Kalajengking batu hitam sebesar rumah yang menyusuri daratan Thalantira. Tubuhnya dapat tersamarkan di antara bongkah vulkanik sampai kaki-kakinya membuka jalan. Bunyi gesekan batu sering mendahului kemunculannya, tetapi di dekat gunung api suara itu mudah tenggelam dalam gemuruh lereng.',
 'Punggungnya terbagi menjadi lempeng hitam berkilap, dengan tepi kasar menyerupai obsidian yang pecah. Kaki beruas keluar rendah dari sisi tubuh dan berakhir pada ujung keras untuk mencengkeram batu. Dua capit besar menggantung di depan, sementara ekor bersegmen melengkung di atas punggung menuju ujung runcing. Sambungan antarbagian tampak lebih gelap daripada lapisannya. Rupa kalajengking dipertahankan tanpa memastikan bahwa sengatnya membawa racun atau bahwa seluruh cangkang dapat diolah seperti batu tambang biasa.',
 'Teritorial, cenderung menahan jalan sebelum menyerang. Ia membuka capit dan menaikkan ekor ketika gangguan mendekat, lalu maju dengan tubuh tetap rendah. Jika terdesak di antara batu, capit dapat dipakai mendorong penghalang atau menjepit apa pun yang berada di depannya. Gerak mundur memberinya ruang untuk mengarahkan kembali tubuh, sehingga bukan pertanda pasti menyerah. Crawler termasuk makhluk darat yang muncul dalam pengungkapan Prologue.',
 'Darat Thalantira merupakan habitat sumber. Hamparan batu tandus di barat dan lereng luar gunung api cocok sebagai usulan penempatan karena menyediakan celah serta permukaan yang menyamarkan cangkang. Lahar ungu tetap menjadi bahaya tersendiri; rupa batu tidak menjadi alasan untuk menganggapnya kebal terhadap aliran tersebut atau hidup di dasar kawah.',
 'Lorong di Bawah Bongkah',
 'Hujan mengisi sebuah celah dengan kerikil. Dari bawah bongkah hitam, capit muncul dan mendorong batu-batu kecil itu keluar. Seekor Crawler menarik tubuhnya ke permukaan, memperlihatkan bahwa yang terlihat seperti lantai gua ternyata punggungnya.\n\nMakhluk yang bersembunyi di dekat mulut celah segera menyingkir. Crawler menahan posisi dengan ekor terangkat sampai jalan di depannya kosong. Setelah itu ia berjalan menuju hamparan batu, dan kilau hujan kembali menyamarkannya di antara bongkah lain.',
 [REG, P8, P9, MOUNTAIN], ['Racun, bahan crafting, dan kekebalan lahar tidak ditetapkan; mikrohabitat serta rupa detail usulan.']),
'Storm_Wyvern': (
 'Naga terbang yang menguasai petir dan badai setempat di langit Thalantira. Ukurannya lebih kecil daripada para penjaga kolosal pulau, tetapi tetap cukup besar untuk mendominasi jalur angin. Kilat yang bergerak melawan arah awan dapat menandai kehadirannya sebelum bentuk sayap terlihat.',
 'Rancangan tubuhnya mengikuti wyvern: sepasang kaki belakang bercakar dan anggota depan yang membentang sebagai sayap. Leher melengkung menyangga kepala bertanduk pendek, sedangkan ekor panjang menjaga keseimbangan ketika tubuh membelok. Sisik kelabu kebiruan menebal di dada dan punggung. Sela duri pada tengkuk memantulkan kilat, dan selaput sayap tampak berurat ketika disinari dari dalam awan. Saat bertengger, ujung sayap dilipat rapat sehingga tubuhnya menyerupai punggung batu bergerigi.',
 'Buas dan sangat mempertahankan jalur terbangnya. Ia berputar mengelilingi penyusup, memperkuat hembusan di sekitarnya, lalu menyambar dari batas awan. Ancaman yang mengejar ke tempat bertengger dapat memancing serangan petir sebelum ia kembali mengudara. Storm Wyvern termasuk penghuni langit yang tampak setelah ilusi pulau tersingkap. Kemiripan wujud dengan naga lain tidak menetapkan hubungan darah dengan Nagarasven maupun kedudukan sebagai keturunan Void Wyrm.',
 'Langit Thalantira dan tebing tinggi yang bersentuhan dengan lapisan badai. Punggung lereng utara cocok sebagai tempat bertengger yang diusulkan, sementara perairan di sekitar benteng karang memberi ruang putar luas. Badai yang menyelimuti seluruh pulau tidak otomatis berasal dari satu Wyvern; batas pengaruh setiap individu belum diceritakan.',
 'Kilat yang Berbelok',
 'Seekor Wyvern mengitari tebing saat awan rendah mendesak masuk. Bayangan bersayap lain melintas terlalu dekat dengan batu tempatnya bertengger. Ia membuka sayap dan naik, mengikuti hembusan yang berputar ke laut.\n\nKilat menyala di sela awan, lalu berpindah mengikuti arah terbangnya. Sang pengganggu menukik menjauh dari tebing sebelum sambaran berikutnya. Wyvern menghentikan pengejaran di atas karang dan kembali ke lereng. Badai terus bergerak, tetapi tempat bertenggernya telah kosong dari bayangan lain.',
 [REG, P8, P9], ['Anatomi detail dan teritorialitas usulan; bukan silsilah Nagarasven/Void Wyrm atau penjelasan tunggal badai pulau.']),
'Thalantira_Gargoyle': (
 'Patung batu bersayap yang dapat meninggalkan tempat bertenggernya dan bergerak sebagai ancaman hidup. Permukaan keras membuat tubuhnya tampak tidak terganggu oleh benturan ringan. Di Thalantira, membedakan hiasan batu dari sesuatu yang sedang mengawasi menjadi sulit ketika sayap terlipat mengikuti bentuk tebing.',
 'Tubuhnya tegap dan berat, dengan lengan bercakar, kepala berahang menonjol, serta kaki yang menekuk untuk mencengkeram tepian. Sepasang sayap batu terlipat bertingkat di belakang bahu seperti bidang pahatan. Retakan tipis dan bercak mineral membedakan permukaannya dari makhluk bersisik. Mata terletak dalam cekungan yang hampir selalu gelap. Saat bergerak, debu jatuh dari lipatan sayap, tetapi tubuh tidak pecah mengikuti garis retak yang terlihat. Wujud tersebut tidak memastikan siapa yang memahat atau membangkitkannya.',
 'Diam untuk mengawasi, lalu agresif ketika ruang yang dijaganya dimasuki. Ia dapat merendahkan kepala, membuka cakar, dan membentangkan sayap sebelum meninggalkan batu. Setelah gangguan menjauh, Gargoyle kembali mencari ketinggian alih-alih terus mengejar tanpa arah. Ini merupakan pengembangan sifat penjagaan dari rupa patung hidupnya. Catatan lama tentang kulit kebal menyatakan ketangguhan, tanpa menjelaskan bahwa semua jenis kekuatan pasti gagal terhadapnya.',
 'Udara Thalantira adalah lokasi sumber. Tepian batu tinggi di dekat jalur kuil diusulkan sebagai tempat bertengger; keberadaan arsitektur kuil mengikuti Prologue. Penempatan ini tidak menambahkan kota yang pernah dihuni atau menganggap semua tebing adalah reruntuhan. Gargoyle tidak disebut khusus dalam daftar makhluk yang tampil saat pengungkapan pulau.',
 'Patung yang Berpindah',
 'Hujan menuruni dinding batu dan membasahi sosok bersayap di tepian atas. Seekor hewan kecil mencari tempat kering di bawahnya. Ketika cakar bergerak, hewan itu berlari meninggalkan ceruk tanpa menoleh.\n\nSayap batu terbuka, menyapu air dalam garis lebar. Gargoyle melayang ke tonjolan lain yang menghadap jalur masuk, lalu membeku kembali dengan kepala menunduk. Di tempat semula tinggal bekas kering berbentuk kaki. Hujan perlahan menghapusnya, sampai tak ada tanda bahwa penjaga itu pernah memilih tempat berbeda.',
 [REG, P7, P8], ['Tidak disebut khusus dalam P9. Pembuat dan sejarah patung belum diketahui; tempat bertengger usulan, bukan bukti peradaban hilang.']),
'Thalantira_Golem': (
 'Makhluk batu kuno yang menjaga kawasan kuil terlarang Thalantira. Wujudnya menyatukan kesan benda tak bergerak dan tubuh yang dapat menghalangi jalan. Nama Golem tidak menjelaskan siapa pembuatnya; di pulau ini, bahkan susunan batu yang tampak sederhana dapat menjadi bagian dari lingkungan yang menyembunyikan keadaan aslinya.',
 'Rancangan tubuh penjaganya tersusun dari bongkah besar: dada lebar, lengan berat, dan kaki pendek yang menapak rata. Kepala masuk di antara bahu, menyisakan celah gelap seperti tempat mata. Permukaan kasar memuat lekuk aus dan mineral pucat yang mengikuti sambungan. Jari-jari tampak seperti potongan batu yang dapat mengatup. Prologue juga memperlihatkan golem kecil setinggi lutut di lorong Kuil Tanah; ukuran itu tidak dipaksakan menjadi ukuran tetap seluruh penjaga batu.',
 'Perilakunya harus dibaca sesuai keadaan pulau. Pada kunjungan awal Hector dan Cassian, golem kecil menjerit dengan decitan batu lalu bersembunyi ketakutan. Pada pengungkapan berikutnya, Golem muncul bersama monster darat yang mengancam. Dalam rancangan penjagaan, tubuh besar menutup lintasan dan bergerak ketika batas ruangnya dilanggar. Belum dipastikan apakah sosok kecil dan besar merupakan individu yang berubah, perbedaan ukuran alami, atau bagian dari penampakan ilusi.',
 'Kawasan kuil di darat Thalantira, dengan lorong bercabang Kuil Tanah sebagai lokasi perjumpaan yang jelas. Ambang ruangan dan jalan berbatu di sekitarnya cocok untuk penempatan penjaga tambahan. Bangunan ini mengikuti cerita Prologue meskipun catatan regional umum menggambarkan pulau tanpa jejak peradaban; keberadaannya tidak menetapkan pencipta atau usia suatu kerajaan.',
 'Suara Kecil di Lorong Batu',
 'Cahaya dari tongkat Cassian memasuki lorong Kuil Tanah. Hector berjalan dengan pedang siap, menunggu sesuatu yang cukup besar untuk menjelaskan keganjilan pulau. Yang muncul justru tubuh-tubuh batu kecil di dekat kaki mereka.\n\nGolem itu menjerit dan berlari menyembunyikan diri. Tidak ada serbuan, hanya decitan yang menghilang di percabangan. Hector menggerutu melihat monster ketakutan pada manusia. Perjalanan mereka berlanjut, tetapi kelucuan singkat itu menjadi bagian lain dari kedamaian yang terlalu mudah diterima sebelum kebenaran pulau terbuka.',
 [P7, P8, P9, WORLD], ['Hubungan golem kecil/besar dan pembuat belum ditetapkan. Konflik catatan wilayah tanpa bangunan vs kuil Prologue dicatat, tidak diselesaikan dengan kerajaan baru.']),
'Void_Harpy': (
 'Makhluk burung-manusia yang memanah energi dari balik awan Thalantira. Siluetnya dapat menyerupai sosok yang menggantung di udara sebelum sayap terbuka. Ia memburu ruang terbuka di bawahnya, tempat sasaran harus memperlihatkan gerakan untuk berpindah dari satu perlindungan ke perlindungan lain.',
 'Kepala dan dada menyerupai manusia, berpadu dengan sayap berbulu gelap yang tumbuh di punggung serta tungkai burung bercakar. Sepasang lengan bebas merentang untuk membentuk lengkung energi seperti busur. Bulu panjang pada pinggang dan ekor mengikuti perubahan arah, sementara wajah sebagian tertutup rambut tipis yang tertiup ke belakang. Cahaya ungu berkumpul di antara kedua tangan sebelum memanjang sebagai anak panah. Susunan anggota tubuh ini adalah rancangan visual untuk mempertahankan kemampuan terbang sekaligus memanah dalam entri lama.',
 'Agresif dari ketinggian dan enggan turun ke jangkauan lawan. Ia melintas di balik kabut, mengubah sudut bidik, lalu menunggu gerakan berikutnya. Jika terancam di udara, Harpy menggunakan cakar untuk mempertahankan ruang sebelum naik lagi. Rupa manusia tidak menjamin kesediaan berunding. Kehadirannya dalam langit pengungkapan Prologue sudah tercatat, tetapi tidak ada dasar untuk menyebutnya anggota Garuda atau keturunan ras bersayap tertentu.',
 'Udara Thalantira, terutama tepian awan di atas tebing dan bukaan hutan sebagai usulan jalur mengintai. Tempat bertengger sempit di dinding batu memberi pandangan ke bawah tanpa menambahkan sarang berupa desa. Kabut serta angin pulau membantunya menyembunyikan perpindahan, walaupun itu bukan bukti bahwa ia mengendalikan seluruh badai.',
 'Panah di Antara Dua Awan',
 'Kabut bergeser di atas sebuah jalur batu. Di bawahnya, seekor makhluk darat meninggalkan bayangan tebing menuju hutan. Garis cahaya muncul dari awan dan menghantam batu tepat di belakangnya.\n\nHarpy melintas ke sisi lain, menarik lengkung bercahaya di antara tangannya. Sasaran telah masuk ke bawah tajuk sebelum anak panah berikutnya dilepas. Ia bertahan di atas bukaan, sayap bergerak melawan angin. Ketika tak ada lagi gerakan di tanah, sosok itu naik dan kembali hilang bersama kabut.',
 [REG, P9], ['Anatomi dengan lengan terpisah adalah usulan visual; bukan hubungan Garuda atau penetapan senjata/drop baru.']),
'Void_Panther': (
 'Macan kosmis yang berpindah seketika untuk menyergap dari arah tak terduga. Jejak kakinya dapat berakhir di tanah terbuka tanpa jalan keluar yang terlihat. Di hutan Thalantira, ketidakhadirannya di depan tidak berarti pemburu ini telah meninggalkan tempat perburuan.',
 'Tubuhnya rendah, panjang, dan lentur, dengan bahu kuat yang bergerak jelas di bawah bulu pendek. Warna hitam pekat memuat kilau ungu samar pada punggung, sedangkan mata terang tetap tampak ketika sisi tubuh lain menyatu dengan gelap. Ekor panjang membantu keseimbangan saat mendarat. Tepian siluet terlihat terurai sesaat sebelum perpindahan, seperti bayangan yang terpotong oleh air. Rahang dan cakar mempertahankan rupa pemangsa kucing besar, tanpa tanduk atau sayap tambahan.',
 'Buas, mengintai, dan lebih memilih celah daripada pertarungan terbuka. Ia mendekat dari tutupan, berhenti ketika diperhatikan, lalu berpindah ke sisi yang tidak diawasi. Jika terluka atau terdesak, kemampuan serupa dipakai untuk melepaskan diri sebelum kembali menilai mangsa. Tubuh yang menghilang tidak selalu berarti serangan akan segera datang. Void Panther termasuk monster darat pada pengungkapan Prologue; kemiripan dengan Macan Kumbang tidak menetapkan bahwa ia hasil mutasi spesies tersebut.',
 'Hutan daratan Thalantira adalah penempatan yang sesuai dengan kategori habitat lama. Jalur berakar, semak rapat, dan tepian bukit di antara pantai serta pusat pulau memberi banyak tempat muncul yang sulit dipantau sekaligus. Batas perpindahannya belum dijelaskan, sehingga tidak ditambahkan jalur teleportasi ke Mandala atau pulau lain.',
 'Jejak yang Berhenti',
 'Seekor hewan berhenti minum ketika melihat dua mata di sela akar. Ia mundur, menjaga kepala tetap menghadap pemangsa. Mata itu lenyap. Sesaat kemudian, ranting patah di belakangnya.\n\nPanther telah muncul di sisi lain genangan. Hewan buruannya melompat ke semak sebelum cakar mencapai air. Percikan jatuh di atas jejak yang hanya terbentuk pada satu tepi. Panther tidak segera mengejar; ia menunduk, mendengarkan gerak daun, lalu menghilang lagi sebelum permukaan genangan kembali tenang.',
 [REG, P7, P9], ['Bukan penetapan asal mutasi Macan Kumbang. Batas teleportasi tidak ditambah; rupa, mikrohabitat, dan kisah usulan.']),
'Void_Wyrm': (
 'Penjaga Kuil Udara di utara Thalantira, seekor wyvern kolosal yang dapat merobek ruang dengan serangannya. Kehadirannya membuat gunung tempat ia muncul tampak terlalu kecil. Di antara tiga penjaga, ia tampil sebagai kakak sulung yang angkuh, lebih cepat menunjukkan kuasa daripada mendengarkan permohonan.',
 'Bentangan sayapnya nyaris menyamai diameter gunung api. Sisik ungu gelap menutupi tubuh, berlawanan dengan perut jingga yang menyerupai lahar menyala. Sayap memancarkan warna merah muda keunguan, sementara tanduk tajam mengelilingi kepala bermata merah. Wujud manusianya berupa ksatria jangkung berzirah perak, dengan jubah dan corak merah tua yang mengingatkan pada sayap naga. Rupa ini mengikuti perjumpaan di kawah, sebelum mutasi paksa Uru merusak penampilan para penjaga.',
 'Sangat agresif terhadap pendatang, arogan kepada kedua adiknya, dan tunduk pada sosok yang mereka panggil Ayah. Ia menyerang Hector serta Cassian bahkan ketika Hydra dan Behemoth mencoba membela mereka. Seruannya melukai, sayapnya mengirim tebasan pembengkok ruang, dan serangannya pernah mengurung kedua penjaga lain sebelum mereka dibebaskan. Kepatuhan pada perintah menghentikan pertempuran tidak mengubahnya menjadi ramah. Setelah pengungkapan Uru, ia kembali memburu; kemudian ia masih mampu berbicara dan meminta izin melanjutkan pengejaran.',
 'Kuil Udara pada kawah gunung api di bagian utara perjalanan Prologue, dihubungkan dengan pusat pulau melalui jalur tebing terjal. Lahar ungu dan angin ganas mengiringi tempat kemunculannya. Kuil Api di selatan baru terkait masa pengabdian Hector kemudian; kedua tempat tidak disamakan. Kedudukan penjaga ini juga tidak menentukan urutan terakhir seluruh kisah Nusvanir.',
 'Emblem dari Tangan yang Enggan',
 'Hydra dan Behemoth telah menghadang serangan kakaknya demi kedua pengunjung. Hector dan Cassian mengira pertolongan itu berakhir ketika kedua penjaga lenyap ditelan kegelapan. Wyrm bersiap menyapu mereka dari bibir kawah.\n\nPerintah dari kuasa yang dihormatinya menghentikan serangan. Naga turun sebagai ksatria perak, lalu membebaskan kedua adiknya. Namun perdebatan masih berlangsung sebelum emblem akhirnya dilemparkan kepada Cassian. Mereka meninggalkan kawah dengan kunci yang dibutuhkan, mengetahui bahwa perjalanan turun itu diizinkan oleh kepatuhan sang penjaga, bukan oleh belas kasihnya.',
 [P8, P9, URU, UNTOLD, MOUNTAIN], ['Label lama Endgame Final Boss bukan penetapan urutan cerita. Void bukan elemen System yang baru. Pemulihan Behemoth tidak dijadikan resurrection gameplay universal.'])
}


def load(path):
    return json.loads(path.read_text(encoding='utf-8-sig'))


def write(path, obj):
    path.write_text(json.dumps(obj, ensure_ascii=False, indent=2) + '\n', encoding='utf-8')


def main():
    archive = REPORT / 'pre_thalantira_narrative.json'
    if archive.exists():
        raise SystemExit('Batch already archived; edit current Markdown directly.')
    paths = sorted(FOLDER.glob('*.json'))
    assert {p.stem for p in paths} == set(ENTRIES)
    old = {p.relative_to(ROOT).as_posix(): p.read_text(encoding='utf-8-sig') for p in FOLDER.iterdir() if p.suffix in ('.md','.json')}
    write(archive, old)
    # Baseline covers user edits and the entire runtime before this controlled batch.
    hashes = {p.relative_to(ROOT).as_posix(): hashlib.sha256(p.read_bytes()).hexdigest() for p in ROOT.rglob('*')
              if p.is_file() and '.git' not in p.parts and '_audit' not in p.parts and '__pycache__' not in p.parts}
    write(REPORT/'pre_thalantira_hashes.json', hashes)
    db = {n:load(GAME/'data'/(n+'.json')) for n in ['Enemies','Skills','Items','Weapons','Armors']}
    for p in paths:
        obj = load(p)
        desc, form, behavior, habitat, story_title, story, sources, unresolved = ENTRIES[p.stem]
        matches = [e for e in db['Enemies'] if e and e['name'] == obj['title']]
        assert len(matches) == 1, p
        enemy = matches[0]
        header = f'---\ntitle: {obj["title"]}\ntags:\n  - Bestiary\n---\n\n# {obj["title"]}\n'
        for heading, content in [('Deskripsi',desc),('Bentuk',form),('Tingkah Laku',behavior),('Habitat',habitat),('Kisah — '+story_title,story)]:
            header += f'\n## {heading}\n\n{content}\n'
        links = []
        for source in sources:
            assert (ROOT/source).is_file(), source
            links.append('[' + Path(source).stem.replace('_',' ') + '](../../' + quote(source, safe='/') + ')')
        note = 'Rincian rupa, perilaku ekologis, dan penempatan habitat tambahan merupakan usulan. Kisah Treant, tiga penjaga, dan Golem merangkum Prologue; kisah makhluk lain merupakan tambahan usulan.'
        header += '\n> Catatan penulisan: ' + note + ' Acuan: ' + '; '.join(links) + '.\n'
        p.with_suffix('.md').write_text(header, encoding='utf-8')
        previous_status = {k:obj.get(k) for k in ['stat_status','balance_status','source_status']}
        obj['stat_status'] = obj['balance_status'] = 'BLOCKED'
        obj['source_status'] = 'legacy_with_runtime_observation'
        obj['presentation'] = {'markdown_role':'lore_only', 'lore_source':p.with_suffix('.md').relative_to(ROOT).as_posix(),
                               'game_data_source':p.relative_to(ROOT).as_posix(),
                               'narrative_status':'PROPOSED_ADDITIONS', 'approval':None,
                               'scope':'New Thalantira additions; Wildlife and Jenggala approvals are not extended to this batch.',
                               'sync_policy':'Author lore in Markdown; game data stays in JSON.'}
        obj['lore_review'] = {'source_archive':archive.relative_to(ROOT).as_posix(),'sources':sources,
                              'unresolved':unresolved,'category_note':'Thalantira endemic category; not a blanket Drahkthar/Jenggala/Bhuta/Dhemit or Voidborn origin. Behavior is contextual to Prologue phases.',
                              'historical_description':obj['description']}
        obj['runtime_observation'] = {'status':'OBSERVED_ONLY','source':(GAME/'data/Enemies.json').relative_to(ROOT).as_posix(),
                                     'enemy':enemy,'skills':[db['Skills'][a['skillId']] for a in enemy['actions']],
                                     'drop_records':[{'database':{1:'Items',2:'Weapons',3:'Armors'}[d['kind']],
                                                      'record':db[{1:'Items',2:'Weapons',3:'Armors'}[d['kind']]][d['dataId']]}
                                                     for d in enemy['dropItems'] if d['kind']],
                                     'meaning':'Snapshot only; does not establish calibrated balance.'}
        obj['balance_review'] = {'stat_status':'BLOCKED','previous_status':previous_status,
                                'legacy_note':'Existing top-level numbers preserved for traceability; not recalibrated.',
                                'authority':'06_Sistem Game & Ekonomi/Pedoman_Pemberian_Stat.md',
                                'simulation_result':None,'playtest_evidence':None,
                                'unresolved':['Approved party/gear/progression and encounter targets absent.',
                                              'Runtime placeholders and modifiers require implementation review before calibration.']}
        write(p,obj)
    print('Thalantira narrative batch: 18 Markdown entries; legacy data and runtime snapshots in JSON.')


if __name__ == '__main__':
    main()
