"""One-time archived narrative batch for Nusa Sayendra sentinels."""
import hashlib, json
from pathlib import Path
from urllib.parse import quote

ROOT=Path(__file__).resolve().parents[1]; BEST=ROOT/'07_Bestiary'; FOLDER=BEST/'07_Sentinels_of_Nusa_Sayendra'; REPORT=BEST/'_audit'; GAME=ROOT/'10_Game Project/Tales of The Dark Time'
WORLD='02_World/Nusa_Sayendra.md'; RACE='04_Ras/02_Wuru Loka/Garuda.md'; CITY='03_Region/07_Nusa Sayendra/Cities & Town/Puncak Emas Swargaloka.md'; FORCE='03_Region/07_Nusa Sayendra/Faksi & Institusi/Pasukan Ksatria Sayap Garuda.md'; OATH='03_Region/07_Nusa Sayendra/Agama & Kepercayaan/Sumpah Penjaga Langit.md'; THREAT='03_Region/07_Nusa Sayendra/Threat.md'

# description, form, personality, station, story title, story, sources, unresolved
ENTRIES={
'Jenderal_Jatayu':(
'Komandan Pasukan Ksatria Sayap Garuda dan veteran perang udara paling berpengalaman di Nusa Sayendra. Jatayu memegang kendali operasional armada ketika Prabu Swarnapatra mulai kehilangan kewarasan akibat kutukan Feral. Petir yang dibawanya bukan sekadar kekuatan perang; di bawah kepemimpinannya, sambaran di langit menjadi isyarat bagi formasi Garuda untuk bergerak sebagai satu kesatuan.',
'Jatayu adalah Garuda raksasa dengan sayap berwarna perunggu yang menyimpan banyak bekas patahan lama. Beberapa bulu tumbuh tidak rata di sepanjang garis luka, membuat bentangan sayapnya mudah dikenali dari jauh. Mata tajam berada di bawah helm berhias bulu badai. Cakar dan paruhnya tampak keemasan kusam, sedangkan listrik merambat sebagai garis putih-biru di antara bulu ketika ia bersiap terbang. Usia serta luka tidak mengurangi wibawanya; keduanya menjadi catatan hidup dari pertempuran yang telah dilalui.',
'Jatayu disiplin, penuh tanggung jawab, dan setia kepada rajanya bahkan ketika tugas itu menuntut keputusan berat. Ia berbicara singkat dalam operasi, tetapi mau mendengar laporan prajurit yang paling muda bila informasi mereka dapat menyelamatkan formasi. Pengalaman membuatnya berhati-hati terhadap keberanian yang tidak disertai rencana. Ia menghormati Ksatria Vayu dari Avalerion dan menjaga aliansi kedua wilayah melalui tindakan nyata. Di balik ketegasannya, ia menyimpan kegelisahan tentang kutukan Swarnapatra dan menolak menyerah mencari obat ke Tirta Amarta.',
'Kuil Angin Selatan Sayendra menjadi pos penjagaan Jatayu dalam entri lama. Dari sana ia mengatur jalur pendekatan armada serta hubungan dengan utusan Avalerion. Pusat komando dan kehidupan Garuda tetap terhubung dengan Puncak Emas Swargaloka, habitat melayang yang memiliki pelataran terbuka. Kuil selatan belum memiliki dokumen geografis tersendiri, sehingga bentuk bangunan, jarak, dan batas wilayahnya tidak diperinci.',
'Perintah di Tengah Petir',
'Awan gelap memutus pandangan antara dua sayap patroli. Seorang prajurit muda mengusulkan pengejaran cepat terhadap bayangan Jenggala yang melintas di bawah badai. Jatayu meminta seluruh formasi menahan posisi sampai kilat berikutnya memperlihatkan jalur.\n\nBayangan itu ternyata umpan; gerombolan lain menunggu di balik lapisan awan. Petir Jatayu membelah gelap sebagai tanda perubahan formasi, dan kedua sayap patroli menutup jalan bersama-sama. Setelah kembali, ia tidak menegur keberanian prajurit muda tersebut. Ia memintanya memimpin pembacaan cuaca berikutnya, agar keberanian itu belajar berjalan bersama kesabaran.',
['05_Karakter & Tokoh Penting/07_Nusa Sayendra/Jenderal Jatayu.md','05_Karakter & Tokoh Penting/03_Avalerion/Ksatria Vayu.md',WORLD,RACE,CITY,FORCE,OATH,THREAT],
['Kuil Angin Selatan belum memiliki dokumen lokasi tersendiri. Ukuran sayap setengah pulau adalah kabar dalam dokumen pasukan, bukan ukuran numerik terverifikasi.']),
'Jenderal_Paksi':(
'Sentinel Garuda yang mengawasi langit timur dengan penglihatan tajam dan resonansi sonik suci. Paksi mengutamakan ketepatan: ia membaca jarak, arah angin, dan gema sebelum melepaskan serangan. Perannya membuat ancaman dapat dikenali saat masih jauh dari pusat Nusa Sayendra, memberi armada waktu untuk memilih tanggapan yang tepat.',
'Tubuh Paksi lebih ramping daripada Garuda garis depan, dengan bulu emas pucat yang menggelap pada ujung sayap. Matanya berwarna terang dan terlindung tonjolan tulang halus agar tetap terbuka saat menembus angin kencang. Ia membawa busur panjang yang dapat digunakan ketika terbang; cahaya dan getaran suara berkumpul pada tali sebelum dilepaskan sebagai bidikan. Penutup dada dibuat rapat agar tidak mengganggu aliran udara. Ketika mendengarkan gema, bulu kecil di sekitar lehernya terangkat mengikuti perubahan tekanan.',
'Paksi teliti, pendiam, dan lebih nyaman menyampaikan kepastian daripada dugaan. Ia dapat terlihat lambat mengambil keputusan karena memeriksa informasi dari beberapa arah, tetapi setelah memilih sasaran ia bertindak tanpa ragu. Ia menghargai pengintai yang berani mengatakan bahwa mereka belum yakin. Sikap perfeksionisnya kadang membuat rekan merasa terus dinilai; ia perlu mengingat bahwa kesalahan latihan adalah bagian dari pembelajaran. Kepada pengunjung, ia sopan namun tidak mudah mengalihkan perhatian dari tugas pengawasan.',
'Kuil Angin Timur Sayendra adalah pos penjagaan Paksi. Arah timur mendapat cahaya awal dan ruang pandang luas, sesuai perannya sebagai pengamat serta pembidik jarak jauh. Ia berpatroli antara kuil dan jalur udara menuju Swargaloka, tetapi bukan berarti semua penerbangan sipil berada di bawah komandonya. Bentuk kuil dan koordinatnya belum mempunyai dokumen regional tersendiri.',
'Gema Sebelum Bayangan',
'Paksi mendengar gema yang kembali terlalu cepat dari awan timur. Pengintai lain tidak melihat apa pun dan mengira perubahan itu hanya akibat angin. Ia meminta mereka menyebar tanpa melepaskan serangan.\n\nKetika matahari naik, cahaya memperlihatkan makhluk yang terbang menempel di bawah lapisan awan. Paksi menembakkan resonansi ke ruang kosong di depannya, memaksa kawanan itu berbelok ke jalur yang telah dijaga. Para Sentinel menghalaunya sebelum mencapai Swargaloka. Paksi mencatat laporan tanpa menyebut dirinya paling dahulu mengetahui ancaman; baginya, pengamatan hanya berguna bila seluruh formasi sempat bertindak.',
[WORLD,RACE,CITY,FORCE,OATH,THREAT],
['Paksi belum memiliki profil tokoh terpisah. Senjata busur, kepribadian, dan kisah merupakan usulan; Kuil Angin Timur belum terdokumentasi sebagai lokasi mandiri.']),
'Jenderal_Sempati':(
'Saudara Jatayu dan Sentinel utara dengan bulu merah menyala yang menyebarkan bara api. Sempati menjadi kekuatan penahan ketika ancaman berusaha memecah formasi udara. Panas yang mengiringi kepakannya menandai batas yang tidak boleh dilewati musuh, sementara kedudukannya sebagai saudara sang komandan tidak menggantikan tanggung jawab pribadi terhadap pasukannya.',
'Sempati bertubuh besar dengan bulu merah-tembaga pada dada dan sayap. Ujung bulu berubah jingga ketika panas meningkat, seolah bara bergerak mengikuti bentangan sayap. Paruhnya tebal, cakar keemasan gelap, dan pelindung bahu menyisakan ruang agar sendi sayap dapat bergerak penuh. Bekas gosong tersebar pada bulu luar akibat latihan di tengah api yang ia ciptakan sendiri. Ia tidak terus menyala; bara muncul ketika tenaga dikumpulkan dan padam perlahan setelah pendaratan.',
'Sempati hangat kepada pasukan yang dikenalnya, terbuka menyampaikan ketidaksetujuan, dan mudah terpancing bila keselamatan keluarganya dipertaruhkan. Ia sering menjadi suara yang lebih langsung dibanding Jatayu. Meski demikian, ia tidak ingin dinilai hanya sebagai saudara komandan dan bekerja keras membangun kepercayaan melalui tugas. Amarahnya dapat memperbesar kekuatan sekaligus mempersempit pertimbangan, sehingga ia mengandalkan perwira lain untuk mengingatkan batas pengejaran. Ia menghormati keberanian yang dipakai melindungi, bukan keberanian yang hanya mencari nama.',
'Kuil Angin Utara Sayendra menjadi pos penjagaan Sempati. Wilayah ini mengawasi arus dingin dan jalur awan yang dapat menyembunyikan pendekatan musuh. Pendar baranya membantu menjaga penanda penerbangan ketika kabut menutup pandangan. Hubungannya dengan Puncak Emas Swargaloka bersifat militer dan spiritual; rincian bentuk Kuil Angin Utara belum ditulis dalam dokumen wilayah.',
'Bara untuk Jalan Pulang',
'Kabut utara menelan penanda yang biasa digunakan patroli untuk kembali. Sempati ingin mengejar kawanan yang baru saja dipukul mundur, tetapi mendengar panggilan dari dua prajurit muda yang kehilangan arah. Ia menghentikan pengejaran dan membentangkan sayap.\n\nBara bergerak dari satu ujung bulu ke ujung lain, membentuk garis merah di dalam kabut. Kedua prajurit mengikuti cahaya itu menuju kuil. Musuh lolos dari jangkauan malam tersebut, namun seluruh patroli pulang. Ketika seorang perwira meminta maaf karena sasaran terlepas, Sempati menjawab bahwa kemenangan yang meninggalkan penjaganya di langit bukan kemenangan yang layak dibawa pulang.',
[WORLD,RACE,CITY,FORCE,OATH,THREAT],
['Sempati belum memiliki profil tokoh terpisah. Hubungan saudara mengikuti entri Bestiary; rupa, kepribadian, dan kisah merupakan usulan.']),
'Jenderal_Suparna':(
'Sentinel barat yang mengendalikan badai salju serta pecahan es di langit Nusa Sayendra. Suparna menggunakan dingin untuk memperlambat ancaman dan membuka ruang bagi formasi lain. Keanggunannya lahir dari kendali gerak yang hemat; ia tidak perlu memenuhi langit dengan serangan ketika perubahan suhu yang tepat dapat mengalihkan seluruh jalur terbang lawan.',
'Suparna memiliki tubuh tinggi dengan bulu emas pucat yang tampak keperakan di bawah awan. Lapisan biru muda mengikuti bagian bawah sayap dan ekor, tempat kristal es sering terbentuk sebelum pecah menjadi serbuk. Lehernya panjang, mata tenang, dan paruh ramping memberi siluet yang berbeda dari Jatayu serta Sempati. Perlengkapan ringan berwarna putih menghindari bagian sendi. Ketika memanggil badai, uap membentuk lingkaran di sekeliling sayap sebelum es bergerigi tumbuh mengikuti arus.',
'Suparna tenang, santun, dan sulit dipancing untuk bertindak tergesa-gesa. Ia lebih suka meredakan pertengkaran dengan menunjukkan akibat setiap pilihan daripada meninggikan suara. Sikap terkendali itu dapat disalahartikan sebagai jarak emosional, padahal ia memperhatikan keadaan pasukan secara rinci. Ia keras terhadap tindakan yang mengorbankan ketelitian demi penampilan. Saat menghadapi ancaman, ia menunggu saat yang memberi hasil terbesar dengan kerusakan paling kecil, lalu bergerak cepat sebelum lawan sempat menyesuaikan diri.',
'Kuil Angin Barat Sayendra adalah pos penjagaan Suparna. Dari sisi barat ia memantau perubahan cuaca dan jalur kembali menuju Puncak Emas Swargaloka. Udara dingin pada lapisan tinggi mendukung pembentukan es tanpa menetapkan bahwa wilayah pulau di bawahnya selalu bersalju. Kuil tersebut belum mempunyai deskripsi regional tersendiri, sehingga rincian arsitektur dan jaraknya tetap terbuka.',
'Es yang Tidak Dijatuhkan',
'Sebuah kawanan Jenggala terbang di atas jalur yang juga dipakai pengangkut telur suci. Suparna telah membentuk pecahan es, tetapi serangan luas akan mengenai rombongan di bawah. Ia menahan badai dan meminta pengawal mengubah ketinggian.\n\nSetelah jalur kosong, Suparna mendinginkan udara di depan kawanan musuh. Sayap mereka menjadi berat oleh kristal, memaksa semuanya turun menjauh dari Swargaloka. Tidak ada hujan es yang jatuh ke pengangkut. Para prajurit muda kemudian memahami bahwa kendali Suparna terlihat bukan hanya dari apa yang dilepaskan, melainkan dari serangan yang sanggup ia tahan sampai waktunya benar.',
[WORLD,RACE,CITY,FORCE,OATH,THREAT],
['Suparna belum memiliki profil tokoh terpisah. Rupa, kepribadian, mekanisme es naratif, dan kisah merupakan usulan.'])}

def load(p): return json.loads(p.read_text(encoding='utf-8-sig'))
def write(p,o): p.write_text(json.dumps(o,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
def main():
 archive=REPORT/'pre_sayendra_sentinels_narrative.json'
 if archive.exists(): raise SystemExit('Batch already archived; edit current files directly.')
 paths=sorted(FOLDER.glob('*.json')); assert {p.stem for p in paths}==set(ENTRIES)
 write(archive,{p.relative_to(ROOT).as_posix():p.read_text(encoding='utf-8-sig') for p in FOLDER.iterdir() if p.suffix in ('.md','.json')})
 write(REPORT/'pre_sayendra_sentinels_hashes.json',{p.relative_to(ROOT).as_posix():hashlib.sha256(p.read_bytes()).hexdigest() for p in ROOT.rglob('*') if p.is_file() and '.git' not in p.parts and '_audit' not in p.parts and '__pycache__' not in p.parts})
 db={n:load(GAME/'data'/(n+'.json')) for n in ['Enemies','Skills','Items','Weapons','Armors']}
 for p in paths:
  o=load(p); desc,form,personality,station,stitle,story,sources,unresolved=ENTRIES[p.stem]
  matches=[e for e in db['Enemies'] if e and e['name']==o['title']]; assert len(matches)==1,p; enemy=matches[0]
  text=f'---\ntitle: {o["title"]}\ntags:\n  - Bestiary\n  - Boss\n---\n\n# {o["title"]}\n'
  for h,c in [('Deskripsi',desc),('Bentuk',form),('Kepribadian dan Sikap',personality),('Kedudukan dan Kuil Penjagaan',station),('Kisah - '+stitle,story)]: text+=f'\n## {h}\n\n{c}\n'
  for s in sources: assert (ROOT/s).is_file(),s
  links=['['+Path(s).stem.replace('_',' ')+'](../../'+quote(s,safe='/')+')' for s in sources]
  text+='\n> Catatan penulisan: Identitas Jatayu mengikuti profil tokoh; kemampuan dan lokasi lama mengikuti entri Bestiary. Rincian tokoh lain serta kisah merupakan usulan. Acuan: '+'; '.join(links)+'.\n'; p.with_suffix('.md').write_text(text,encoding='utf-8')
  prev={k:o.get(k) for k in ['stat_status','balance_status','source_status']}; o['stat_status']=o['balance_status']='BLOCKED'; o['source_status']='legacy_with_runtime_observation'; o['race']='Garuda'
  o['presentation']={'markdown_role':'lore_only','lore_source':p.with_suffix('.md').relative_to(ROOT).as_posix(),'game_data_source':p.relative_to(ROOT).as_posix(),'narrative_status':'PROPOSED_ADDITIONS','approval':None,'scope':'Four Nusa Sayendra sentinels; earlier approvals do not extend to this batch.','sync_policy':'Author lore in Markdown; game data stays in JSON.'}
  o['lore_review']={'source_archive':archive.relative_to(ROOT).as_posix(),'sources':sources,'unresolved':unresolved,'category_note':'Sapient Garuda sentinels; cardinal temples retained as duty stations, not new settlements.','historical_description':o['description']}
  o['runtime_observation']={'status':'OBSERVED_ONLY','source':(GAME/'data/Enemies.json').relative_to(ROOT).as_posix(),'enemy':enemy,'skills':[db['Skills'][a['skillId']] for a in enemy['actions']],'drop_records':[{'database':{1:'Items',2:'Weapons',3:'Armors'}[d['kind']],'record':db[{1:'Items',2:'Weapons',3:'Armors'}[d['kind']]][d['dataId']]} for d in enemy['dropItems'] if d['kind']],'meaning':'Snapshot only; does not establish calibrated balance.'}
  o['balance_review']={'stat_status':'BLOCKED','previous_status':prev,'legacy_note':'Existing top-level numbers preserved; not recalibrated.','authority':'06_Sistem Game & Ekonomi/Pedoman_Pemberian_Stat.md','simulation_result':None,'playtest_evidence':None,'unresolved':['Approved party/gear/progression and encounter targets absent.','Runtime implementation requires review before calibration.']}; write(p,o)
 print('Sayendra sentinels narrative batch: 4 Markdown entries; game data retained in JSON.')
if __name__=='__main__': main()
